language: php
php:
  - '7.2'
  - nightly
install:
  - composer install

script:
  - mkdir -p build/logs
  - php vendor/bin/phpunit -c phpunit.xml.dist

after_success:
  # or enable logging
  - travis_retry php vendor/bin/php-coveralls -v