language: php
sudo: false
php:
  - '7.2'
  - nightly
install:
  - composer install
  - wget https://github.com/satooshi/php-coveralls/releases/download/v1.0.0/coveralls.phar

before_script:
  - mkdir -p build/logs

script:
  - vendor/bin/phpunit --coverage-clover build/logs/clover.xml

after_script:
  - php coveralls.phar -v

notifications:
    email: false